// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqb0gnm8qPJxKchgFpZtYqtkD9K-7Xwjs',
    appId: '1:867004928263:web:ffe8e1f2f0a975439275a2',
    messagingSenderId: '867004928263',
    projectId: 'gitsync-645b3',
    authDomain: 'gitsync-645b3.firebaseapp.com',
    storageBucket: 'gitsync-645b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeK8yDlHiEx3WHAdHee-L3gasGJlm0LAc',
    appId: '1:867004928263:android:640a3c49797c0d559275a2',
    messagingSenderId: '867004928263',
    projectId: 'gitsync-645b3',
    storageBucket: 'gitsync-645b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDamWAVxqHXsOcH9FvPT0Fadl7Bu-AKcyg',
    appId: '1:867004928263:ios:56e41582d2d11d6d9275a2',
    messagingSenderId: '867004928263',
    projectId: 'gitsync-645b3',
    storageBucket: 'gitsync-645b3.firebasestorage.app',
    iosBundleId: 'com.example.gitsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDamWAVxqHXsOcH9FvPT0Fadl7Bu-AKcyg',
    appId: '1:867004928263:ios:56e41582d2d11d6d9275a2',
    messagingSenderId: '867004928263',
    projectId: 'gitsync-645b3',
    storageBucket: 'gitsync-645b3.firebasestorage.app',
    iosBundleId: 'com.example.gitsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqb0gnm8qPJxKchgFpZtYqtkD9K-7Xwjs',
    appId: '1:867004928263:web:dbe841d8290b8d889275a2',
    messagingSenderId: '867004928263',
    projectId: 'gitsync-645b3',
    authDomain: 'gitsync-645b3.firebaseapp.com',
    storageBucket: 'gitsync-645b3.firebasestorage.app',
  );
}
